name: loan_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.1.0+2

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  pin_code_fields: ^7.4.0
  syncfusion_flutter_signaturepad: ^23.2.7
  http: ^1.2.0
  logger: ^2.0.2+1
  intl_phone_field: ^3.1.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.4
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.15.0
  change_app_package_name: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - asset/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
