Map<String, String> strings = {
  "24HoursOnline": "24 hours online",
  "aboutUs": "About Us",
  "accountNumber": "Account Number",
  "anyFamilyMemberName": "Any Family Member Name",
  "appVersion": "App Version",
  "balance": "Balance",
  "bankAccountValidation": "Bank Account Validation",
  "bankAccountVerification": "Bank account verification",
  "bankName": "Bank Name",
  "bdt": "BDT",
  "branchName": "Branch Name",
  "changeAccountPassword": "Change Account Password",
  "clear": "Clear",
  "clickToReviewTheLoanAgreement": "Click to review the loan agreement",
  "commonProblems": "Common Problems",
  "confirmNewPassword": "Confirm new password",
  "confirmPassword": "Confirm password",
  "contact": "Contact",
  "createAnAccount": "Create An Account",
  "customerCare": "Customer Care",
  "customerService": "Customer Service",
  "cycle": "CYCLE",
  "dataValidation": "Data Validation",
  "details": "Details",
  "doYouOwnACar": "Do you own a car",
  "doYouOwnAHouse": "Do you own a house",
  "don'tHaveAnAccount?": "Don't have an account?",
  "duration": "DURATION",
  "education": "Education",
  "eligibilityValidation": "Eligibility Validation",
  "enterNewPassword": "Enter new password",
  "enterRechargeAmount": "Enter Recharge Amount",
  "enterWithdrawAmount": "Enter Withdraw Amount",
  "enterWithdrawalCode": "Enter Withdrawal Code",
  "enterYourOldPassword": "Enter your old password",
  "estimatedLoan": "ESTIMATED LOAN",
  "familyMember": "Family Member",
  "forALoan": "For a Loan",
  "forgotPassword": "Forgot password",
  "friendNumber": "Friend Number",
  "guardiantNumber": "Guardiant Number",
  "help": "Help",
  "home": "Home",
  "idCardValidation": "ID Card Validation",
  "idCardVerification": "ID Card Verification",
  "idNumber": "ID Number",
  "interestType": "INTEREST TYPE",
  "interest": "INTEREST",
  "loanAmount": "Loan Amount",
  "loanChoice": "Loan Choice",
  "loanDetails": "Loan Details",
  "loanDuration": "Loan Duration",
  "loanPurpose": "Loan Purpose",
  "loanRecords": "Loan Records",
  "loan": "Loan",
  "loaned": "Loaned",
  "logOut": "Log Out",
  "login": "Login",
  "maximumBorrowableAmount": "MAXIMUM BORROWABLE AMOUNT",
  "mobileBanking": "Mobile Banking",
  "monthlyIncome": "Monthly Income",
  "myDebts": "My Debts",
  "myWallet": "My Wallet",
  "name": "Name",
  "newPassword": "New Password",
  "noHistoryAvailable": "No History Available",
  "no": "No",
  "occupation": "Occupation",
  "oldPassword": "Old Password",
  "onlineBanking": "Online Banking",
  "onlineRecharge": "Online Recharge",
  "password": "Password",
  "personalInfo": "Personal Info",
  "phoneNumberValidation": "Phone Number Validation",
  "phoneNumber": "Phone Number",
  "pickImageFromGallary": "Pick Image From Gallary",
  "pleaseSelectTheLoanAmountAndInstallmentMonthPassTheReviceAndWithdrawWithin6HoursAtTheFastest.":
      "Please select the loan amount and installment month, pass the revice and withdraw within 6 hours at the fastest.",
  "profile": "Profile",
  "rechageAmount": "Rechage Amount",
  "recharge": "Recharge",
  "registration": "Registration",
  "request": "Request",
  "required": "required",
  "seeYourInformation": "See your information",
  "selectOnlineBank": "Select Online Bank",
  "settings": "Settings",
  "signatureValidation": "Signature Validation",
  "signature": "Signature",
  "submit": "Submit",
  "takePhotoFromCamera": "Take Photo From Camera",
  "theBankProvidesSecurityForYourAccount": "The bank provides security for your account",
  "theHighestCanApplyBDT": "The highest can apply BDT",
  "toReceiveOurInformationPleaseFillTheFollowingInformationTruthfully": "To receive our information, please fill the following information truthfully.",
  "uploadImage": "Upload Image",
  "uploadSelfieToEnsureYourIdentification": "Upload selfie to ensure your identification",
  "uploadTheBackSidePhotoOfYourIDCard": "Upload the back side photo of your ID card",
  "uploadTheFrontSidePhotoOfYourIDCard": "Upload the front side photo of your ID card",
  "userName": "User Name",
  "userNumber": "User Number",
  "verificationOfEligibility": "Verification of Eligibility",
  "verifyPersonalInformation": "Verify Personal Information",
  "visit": "Visit",
  "walletBalance": "Wallet balance",
  "wallet": "Wallet",
  "withdrawAmount": "Withdraw Amount",
  "withdrawMoney": "Withdraw Money",
  "withdraw": "Withdraw",
  "withdrawalCode": "Withdrawal Code",
  "writeBankAccountBranchName": "Write Bank Account Branch Name",
  "writeBankAccountHolderName": "Write Bank Account Holder Name",
  "writeBankAccountNumber": "Write Bank Account Number",
  "writeBankName": "Write Bank Name",
  "writeContactNumber": "Write Contact Number",
  "writeGurdianContactNumber": "Write Gurdian Contact Number",
  "writePurposeOfTheLoan": "Write Purpose of the Loan",
  "writeYourContactNumber": "Write Your Contact Number",
  "writeYourEducation": "Write Your Education",
  "writeYourFriendsContactNumber": "Write Your Friend's Contact Number",
  "writeYourMonthlyIncome": "Write Your Monthly Income",
  "writeYourName": "Write Your Name",
  "writeYourOccupation": "Write Your Occupation",
  "writeYourValidIDNumber": "Write your valid ID Number",
  "yes": "Yes",
  "yourWallet": "Your Wallet",
  // New Added String (missing)
  "validity": "Validity",
  "months": "Months",
  "lowInterest": "LOW INTEREST",
  "forAnyKindOfInformation": "For any kind of information",
  "rechargeOption": "Recharge Option",
};
